### ISSUE TITLE
点击DatePicker闪退

### ISSUE THREAD

**Issue by yanghuabang05** [simplepeng/PickerLayoutManager#2]
虚拟机Android 版本10.0，报这个错误 java.lang.IndexOutOfBoundsException: Invalid item position 1(1). Item count:1 me.simple.picker.datepicker.MonthPickerView{2097f5e VFED..... ......ID 343,0-686,375}, adapter:me.simple.picker.widget.TextPickerView$TextPickerAdapter@c3fab83, layout:me.simple.picker.PickerLayoutManager@7b02100, context:demo.simple.picker.DatePickerActivity@8d0292d

**Comment by libaitian-li** [comment]
同问这个问题，今天更新的，现在是否解决了呢？

**Comment by simplepeng** [comment]
@yanghuabang05 @libaitian-li 没复现bug成功，有具体的错误日志吗

**Comment by simplepeng** [comment]
@yanghuabang05 @libaitian-li 已修复
